export const DomainErrorCode = {
  ADMIN_REQUIRED: "ADMIN_REQUIRED",
  DUPLICATED_GROUP_TEAM: "DUPLICATED_GROUP_TEAM",
  DUPLICATED_STANDING_POSITION: "DUPLICATED_STANDING_POSITION",
  INVALID_BEST_THIRDS_COUNT: "INVALID_BEST_THIRDS_COUNT",
  MATCH_NOT_CONFIRMED: "MATCH_NOT_CONFIRMED",
  MATCH_NOT_EDITABLE: "MATCH_NOT_EDITABLE",
  PREDICTION_LOCKED: "PREDICTION_LOCKED",
  PREDICTION_NOT_ENABLED: "PREDICTION_NOT_ENABLED",
  PREDICTION_NOT_FOUND: "PREDICTION_NOT_FOUND"
} as const;

export type DomainErrorCode = (typeof DomainErrorCode)[keyof typeof DomainErrorCode];
